#2 changed body color to darkblue
INWT/inwt-quarto-template-presentation pull request #3
Opened 2023-07-19 12:32 UTC by freimanninwt

So, das ist schonmal die erste von 2 Anpassungen:

![image](https://github.com/INWT/inwt-quarto-template-presentation/assets/124151087/82443d0d-8f56-4244-ac85-cc9bd3aa9eee)

Wir müssen nicht zwingend orange Bulletpoints verwenden, aber die könnte ich bei Gelegenheit auch reinbauen.

2023-07-19 15:50 UTC, jan-abel-inwt commented
Und bitte das nächste mal mich als Reviewer eintragen ;)

2023-07-19 15:51 UTC, jan-abel-inwt requested changes
Habe dir die Änderung oben Beschrieben

2023-08-01 07:42 UTC, freimanninwt commented
@jan-abel-inwt: `format: inwt-presentation-revealjs` musste ich in der _quarto.yml lassen, sonst spuckt er mir die Präsi nach dem Renderbefehl in einem anderen .html Format aus.

2023-08-01 11:37 UTC, jan-abel-inwt commented
Was mir noch aufgefallen ist:

- [x] Der `partials` Ordner lebt natürlich im `inwt-presentation` Ordner, da er ja zu der Extension gehört
- [x] Das date-format war mit Leerzeichen definiert. Ich habe das korrigiert und die Option in die _extension.yml verschoben 
- [ ] Es fehlt noch die Fullstack Data Science Folie (siehe google presentation)
- [ ] Die letzte Seite ist beim kaputt:
       ![image](https://github.com/INWT/inwt-quarto-template-presentation/assets/106665518/dbbbfe4f-25cd-411a-adac-1c5e295d1af4)
      Ist das bei dir auch so?
- [ ] Bitte die Readme anpassen: so wie hier https://github.com/INWT/inwt-quarto-template-report/blob/main/readme.md

2023-08-01 11:50 UTC, freimanninwt commented
@jan-abel-inwt: 
![image](https://github.com/INWT/inwt-quarto-template-presentation/assets/124151087/32ba5902-9bc6-4367-a329-089c8c71b13d)

Ich habe diesen Rand nicht. Mir ist noch aufgefallen, dass die Page Numbers so eine unschöne blaue Farbe haben, die ändere ich noch in ein `sage green`.

2023-08-02 09:42 UTC, freimanninwt commented
@jan-abel-inwt @chamaoskurumi, das mit den zwei partials hat doch nicht so funktioniert, wie ich dachte. Man kann nur ein ganzes template.html, eine title-slide.html sowie eine toc-slide.html einbinden (Jan hat bereits etwas in die Richtung geäußert). Dass es gestern geklappt hat, entspricht nicht dem Normalfall. 

Ich habe die claim-page also zur title-slide.html hinzugefügt und in der README beschrieben, was man löschen muss, wenn diese Folie nervt.
  
![image](https://github.com/INWT/inwt-quarto-template-presentation/assets/124151087/f39380d5-0520-456b-897b-c661ad9928be)

Man kann übrigens im YAML eine Variable festlegen, die das Erscheinen der title-page, nicht aber der claim-page kontrolliert :(

2023-08-07 08:20 UTC, jan-abel-inwt commented
Mir ist noch ein kleine Sache beim auführen von `quarto render` aufgefallen: Die Code-Chunks sind nicht benamt (`unamed-chank-x`). Könntest du dort noch aussagekräftige Namen verteilen?

```                                                                                               
processing file: template_presentation.qmd
1/11                  
2/11 [unnamed-chunk-1]
3/11                  
4/11 [unnamed-chunk-2]
5/11                  
6/11 [unnamed-chunk-3]
7/11                  
8/11 [unnamed-chunk-4]
9/11                  
10/11 [unnamed-chunk-5]
11/11                  
output file: template_presentation.knit.md

pandoc 
  to: revealjs
  output-file: template_presentation.html
  standalone: true
  embed-resources: true
  wrap: none
  default-image-extension: png
  html-math-method:
    method: mathjax
    url: >-
```

2023-08-11 12:34 UTC, jan-abel-inwt commented
Ich finde das übrigens in Ordnung so wie du das mit der claim page gelöst hast und würde sagen die bleibt halt immer drin. Was wäre denn der use-case wo sie stark stören würde?

2023-08-15 09:54 UTC, freimanninwt commented
@jan-abel-inwt Evtl. wenn man immer vor dem gleichen Personenkreis präsentiert. Da könnte man sich fragen, warum die Folie noch drin ist. Aber man kann es auch einfach skippen.

2023-08-15 11:10 UTC, jan-abel-inwt approved these changes
supi!

2023-08-15 11:11 UTC, jan-abel-inwt commented
> @jan-abel-inwt Evtl. wenn man immer vor dem gleichen Personenkreis präsentiert. Da könnte man sich fragen, warum die Folie noch drin ist. Aber man kann es auch einfach skippen.

Das traue ich den vortragenden Personen zu ;)

2023-08-15 14:54 UTC, merged